management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

database:
  url: "jdbc:postgresql://172.18.0.2:5430/demoDB"
  user: "usr"
  pwd: "pwd"
