management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

database:
  url: "jdbc:postgresql://0.0.0.0:5432/demoDB"
  user: "usr"
  pwd: "pwd"